@echo off
echo Starting Construction Planning System...
echo Ensuring virtual environment is active...
call venv\Scripts\activate
echo Installing/Updating dependencies...
pip install -r requirements.txt
echo Starting Server...
python server.py
pause
